[critical_protection]
name = "Critical Protection"
description = "This enchantment is currently available to only two helms: both versions of Fur-Ear Flap helm from New Year 2018 and 2021. The helm Iron Mask which was obtainable from the Starter Pack prior to version 1.6.1 was also initially enchanted with Critical Protection, however, it still can be added with Stalker."

[critical_protection.equipment_ids]
armor = "PERK_ITEM_SPECIAL_CRITICAL_PROTECTION_ARMOR"
helm = "PERK_ITEM_SPECIAL_CRITICAL_PROTECTION_HELM"

[precision]
name = "Precision"

[precision.equipment_ids]
weapon = "PERK_ITEM_SPECIAL_PRECISION_WEAPON"
ranged = "PERK_ITEM_SPECIAL_PRECISION_RANGED"
magic = "PERK_ITEM_SPECIAL_PRECISION_MAGIC"

[overheat]
name = "Overheat"

[overheat.equipment_ids]
weapon = "PERK_ITEM_SPECIAL_OVERHEAT_WEAPON"
ranged = "PERK_ITEM_SPECIAL_OVERHEAT_RANGED"
magic = "PERK_ITEM_SPECIAL_OVERHEAT_MAGIC"
armor = "PERK_ITEM_SPECIAL_OVERHEAT_DEFENSE_ARMOR"
helm = "PERK_ITEM_SPECIAL_OVERHEAT_DEFENSE_HELM"

[poisoning]
name = "Poisoning"

[poisoning.equipment_ids]
weapon = "PERK_ITEM_SPECIAL_INTOXICATION_WEAPON"
ranged = "PERK_ITEM_SPECIAL_INTOXICATION_RANGED"
magic = "PERK_ITEM_SPECIAL_INTOXICATION_MAGIC"

[weakness]
name = "Weakness"

[weakness.equipment_ids]
weapon = "PERK_ITEM_SPECIAL_WEAKNESS_WEAPON"
ranged = "PERK_ITEM_SPECIAL_WEAKNESS_RANGED"
magic = "PERK_ITEM_SPECIAL_WEAKNESS_MAGIC"

["magic_recharge"]
name = "Magic Recharge"

[magic_recharge.equipment_ids]
weapon = "PERK_ITEM_SPECIAL_MAGIC_DAMAGE_RECHARGE_WEAPON"
armor = "PERK_ITEM_SPECIAL_MAGIC_PAIN_RECHARGE_ARMOR"
helm = "PERK_ITEM_SPECIAL_MAGIC_PAIN_RECHARGE_HELM"

[bloodrage]
name = "Bloodrage"

[bloodrage.equipment_ids]
weapon = "PERK_ITEM_SPECIAL_BLOODRAGE_WEAPON"
ranged = "PERK_ITEM_SPECIAL_BLOODRAGE_RANGED"
magic = "PERK_ITEM_SPECIAL_BLOODRAGE_MAGIC"

[rejuvenation]
name = "Rejuvenation"

[rejuvenation.equipment_ids]
armor = "PERK_ITEM_SPECIAL_REJUVENATION_ARMOR"
helm = "PERK_ITEM_SPECIAL_REJUVENATION_HELM"

[damage_absorption]
name = "Damage Absorption"

[damage_absorption.equipment_ids]
armor = "PERK_ITEM_SPECIAL_DAMAGE_ABSORPTION_BODY_ARMOR"
helm = "PERK_ITEM_SPECIAL_DAMAGE_ABSORPTION_HEAD_HELM"
